apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: pe-owned-templates
  description: Templates and entities owned by the Platform Engineering team
spec:
  targets:
    - ./templates/argocd-app-template/template.yaml
    - ./templates/sample-template/template.yaml
    - ./templates/parasol-insurance-secured/template.yaml
    - ./entities/system.yaml
    - ./entities/api.yaml
    - ./entities/components.yaml
