apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: parasol-insurance-secured-dev
  title: Parasol Insurance Secured Development
  description: Create a secured development sandbox for the Parasol Insurance app
  tags:
    - parasol
    - secured
    - development
spec:
  owner: rhdh
  type: service

  parameters:
    - title: Development Branch
      required:
        - branch
      properties:
        branch:
          title: Branch Name
          type: string
          description: Branch name in the parasol-insurance source repo

  steps:
    - id: create-branch
      name: Create Source Branch
      action: gitlab:repo:push
      input:
        repoUrl: {{ gitlab_host }}?repo=parasol-insurance&owner=parasol
        branchName: ${{ parameters.branch }}
        commitMessage: 'Scaffolder commit initializing branch "${{ parameters.branch }}"'
        commitAction: create

    - id: fetch-skeleton
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./manifests/
        values:
          namespace: parasol-insurance-secured-${{ user.entity.metadata.name }}
          branch: ${{ parameters.branch }}
          source_repo: https://{{ gitlab_host }}/parasol/parasol-insurance.git
          owner: ${{ user.entity.metadata.name }}
          image_host: {{ quay_host }}
          image_organization: parasol
          image_name: parasol-insurance-secured-${{ user.entity.metadata.name }}
          image_tag: latest
          gitlab_host: {{ gitlab_host }}
          cluster_subdomain: {{ cluster_subdomain }}
          gitops_namespace: {{ rhdh_gitops_namespace }}
          dev_email: ${{ user.entity.spec.profile.email }}

    - id: publish
      name: Publish to GitLab
      action: publish:gitlab
      input:
        repoUrl: {{ gitlab_host }}?owner=${{ user.entity.metadata.name }}&repo=parasol-insurance-secured-${{ parameters.branch }}-gitops
        defaultBranch: main
        repoVisibility: public

    - id: create-argocd-resources
      name: Create ArgoCD Resources
      action: backstage-community-argocd:create-resources
      input:
        appName: parasol-insurance-secured-${{ user.entity.metadata.name }}-${{ parameters.branch }}-bootstrap
        argoInstance: main
        namespace: {{ rhdh_gitops_namespace }}
        repoUrl: ${{ steps.publish.output.remoteUrl }}.git
        path: argocd

    - id: register
      name: Register Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: GitOps Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
